### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by Bambofy** [ChrisDill/Raylib-cs#23] opened 2019-03-05 13:29 UTC
Loading the library causes a huge memory leak on running the default project.

**Comment by msmshazan** [comment] 2019-03-06 08:03
Which operating system?

**Comment by Bambofy** [comment] 2019-03-07 09:03
http://richardbamford.io/dmp/958M0MFHvl.mp4

**Comment by ChrisDill** [comment] 2019-03-07 12:04
Try this in your loop.
```csharp
BeginDrawing();
ClearBackground(Color.SKYBLUE);
EndDrawing();
```

**Comment by Bambofy** [comment] 2019-03-08 09:47
Works! thanks :) awesome library.

**Comment by msmshazan** [comment] 2019-03-13 18:44
@Bambofy please close the issue if the problem is solved :)

**Closed** 2019-03-13 18:57 UTC
